### ISSUE TITLE
Fix Fisher configuration files check

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh-plugin-fish-fisher#4]
The check to see if the Fisher configuration files already exist seems to have been broken by recent commits, as it re-installs Fisher each time I `xxh` into a remote host.

**Comment by frederickjh** [comment]
fisher has changed where it stores its configuration from `$XDG_CONFIG_HOME/fish/fishfile` to `$XDG_CONFIG_HOME/fish/fish_plugins´. This needs to be changed in two places in  `[xxh-plugin-fish-fisher/fish/conf.d/fisher.fish](https://github.com/xxh/xxh-plugin-fish-fisher/blob/56bd6fdde86f3ffc8f806c92e4345dd54aac25d3/fish/conf.d/fisher.fish#L4-L6)`.

**Comment by anki-code** [comment]
Thanks for reporting @frederickjh ! PR is very welcome!

**Comment by frederickjh** [comment]
@anki-code  More a note to myself than anything. I hope to close this issue soon.

**Comment by frederickjh** [comment]
The line that checks `$XDG_CONFIG_HOME/fisher/local` needs changed too.
